spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/concert_reservation?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
      username: sa
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS concert_reservation;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6380
logging:
  level:
    org:
      springframework:
        kafka: DEBUG

topic:
  name: my-topic
#logging:
#  level:
#    org:
#      springframework:
#        transaction:
#          interceptor: TRACE
#        jdbc:
#          datasource:
#            DataSourceTransactionManager: DEBUG
#        orm:
#          jpa:
#            JpaTransactionManager: DEBUG
#      hibernate:
#        resource:
#          transaction: DEBUG
#        SQL: DEBUG
---
schedule:
  userToken:
    success:
      cron: "* */10 * * * *"
      active: false
    expire:
      cron: "* */10 * * * *"
      active: false
  reserveSeat:
    restore:
      cron: "* */5 * * * *"
      active: false
  outbox:
    re-publish:
      cron: "* */10 * * * *"

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumer-group01
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual

topic:
  name: my-topic